### ISSUE TITLE
我创建了一个新分支，但无法pull requests

### ISSUE THREAD

**Issue by Jarmaginer** [2b-creator/SeewoLamp#1]
new branch：master
使用NanUI的分支

**Comment by 2b-creator** [comment]
> new branch：master
> 
> 使用NanUI的分支

why？

**Comment by 2b-creator** [comment]
> new branch：master 使用NanUI的分支

我来添加分支吧，或许是Settings内出了问题，你可以到discuss那边提出

**Comment by 2b-creator** [comment]
The responsitory was moved to Jar-WEI.
